#!/bin/bash

source /etc/default/refind || [[ $(echo "Can't find /etc/default/refind, please check again" && exit 1) ]]
ESP=$(cat /etc/fstab | awk '{print $1}' | grep "EFI" | sed 's|EFI.*||g')
BOOT="EFI/refind"
[[ -z $ICONS ]] && ICONS="icons" || ICONS="icons/icons-$ICONS"

if [[ $CHECK_UCODE = "true" ]]; then
    _ucode=$(ls /boot | grep ucode 2>/dev/null)
    if [[ $_ucode = "amd-ucode.img" ]]; then
        ucode='initrd=\\amd-ucode.img'
    elif [[ $_ucode = "intel-ucode.img" ]]; then
        ucode='initrd=\\intel-ucode.img'
    fi
fi

generate_menuentry() {
    os_icon=$(echo "$1" | tr [:upper:] [:lower:])
    if [[ ! $(ls /boot | grep $DEFAULT_KERNEL 2>/dev/null) ]]; then
        echo "$DEFAULT_KERNEL not found in /boot. Automatically setting default kernel..."
        DEFAULT_KERNEL=$(ls /boot | grep "vmlinuz-linux\|vmlinuz-linux-zen\|vmlinuz-linux-hardened\|vmlinuz-linux-lts" | cut -d "-" -f 2- | awk 'IF NR==1 {print $1}')
    fi
    main_entry="\n${main_entry}menuentry \"$1\" {\n"
#    [[ -f $ESP/$BOOT/$ICONS/os_$os_icon.png ]] && main_entry+="\ticon $BOOT/$ICONS/os_$os_icon.png \n"
    [[ -n $volume ]] && main_entry+="\tvolume $2\n"
    main_entry+="\tostype Linux\n"
    main_entry+="\tloader EFI/$os_icon/vmlinuz-$DEFAULT_KERNEL\n"
    main_entry+="\tinitrd EFI/$os_icon/initramfs-$DEFAULT_KERNEL.img\n"
    main_entry+="\toptions \"root=$root $REFIND_CMDLINE_LINUX $REFIND_CMDLINE_LINUX_DEFAULT $ucode\"\n"
    main_entry+="\tsubmenuentry \"Boot using safe graphics\" {\n"
    main_entry+="\t\tinitrd /initramfs-$DEFAULT_KERNEL-safegraphics.img\n"
    main_entry+="\t\toptions \"root=$root rw add_efi_memmap $REFIND_CMDLINE_LINUX_DEFAULT\"\n\t}\n"
}

generate_submenuentry() {
    sub_entry+="\tsubmenuentry \"$1\" {\n"
    sub_entry+="\t  loader $BOOT/vmlinuz-$1\n"
    sub_entry+="\t  initrd $BOOT/initramfs-$1.img\n"
    sub_entry+="\t  options \"root=$root rw add_efi_memmap $REFIND_CMDLINE_LINUX $REFIND_CMDLINE_LINUX_DEFAULT $ucode\" \n\t}"
    printf "%s" "$sub_entry\n"
}

generate_otheros() {
    if [[ $(echo -e "$main_entry" | grep -w "\"$1\"") ]]; then
        main_entry+="\tsubmenuentry \"$1 $3\" {\n"
        main_entry+="\t\tinitrd /EFI/$1/$3 \n\t"
        main_entry+="\toptions \"root=$4 $REFIND_CMDLINE_LINUX $REFIND_CMDLINE_LINUX_DEFAULT $ucode\"\n\t}\n\t"
    else
        os_icon=$(echo "$1" | tr [:upper:] [:lower:])
        main_entry="\n${main_entry}menuentry \"$1\" {\n"
#        [[ -f $ESP/$BOOT/$ICONS/os_$os_icon.png ]] && main_entry+="\ticon $BOOT/$ICONS/os_$os_icon.png \n"
        main_entry+="\tostype Linux\n"
        main_entry+="\tloader EFI/$1/$2\n"
        main_entry+="\tinitrd EFI/$1/$3\n"
        main_entry+="\toptions \"root=$4 $REFIND_CMDLINE_LINUX $REFIND_CMDLINE_LINUX_DEFAULT $ucode\"\n"
    fi
}

dev=$(mount | grep "/boot " | awk '{print $1}')
root=$(mount | grep -w '/' | awk '{print $1}' | rev | cut -d '/' -f 1 | rev)
is_lvm=$(sudo lvs -o lv_name | awk '{if(NR>1)print}' | tr -d " " | while read lv; do findmnt -l | grep '/dev/\S\+' | awk '{print $2}' | grep $lv; done)

[[ ! -z $is_lvm ]] && root="/dev/mapper/$root" || root="/dev/$root"

generate_menuentry "$OS_DISTRIBUTOR"
sub=$(ls /boot | grep "vmlinuz" | cut -d "-" -f 2- | while read k; do
    [[ $k != $DEFAULT_KERNEL ]] && generate_submenuentry $k
done)
main_entry="$main_entry$sub}\n"

oses=$(ls /efiboot/EFI | grep -v "refind\|tools\|phyos")
_osprober=$(sudo os-prober)

for os in $oses; do
    kernels=$(ls /efiboot/EFI/$os | grep "vmlinuz" | cut -d "-" -f 2- | sort -r)
    for kern in $kernels; do
        loader="vmlinuz-$kern"
        main_ent=$(ls /efiboot/EFI/$os | grep "initramfs" | grep -w $kern || ls /efiboot/EFI/$os | grep "initrd" | grep "$kern")
        root=$(echo "$_osprober" | grep -i "$os" | cut -d ":" -f 1)
        for r in $root; do
            generate_otheros "$os" "$loader" "$main_ent" "$r"
        done
    done
    main_entry+="\n}\n"
done

BOOT="$ESP/$BOOT"
echo -e "$main_entry" | sudo tee $BOOT/refind_entries.conf
sudo cp -rf /etc/refind.d/refind.conf $BOOT/refind.conf
echo "icons_dir $ICONS" | sudo tee -a $BOOT/refind.conf
echo "include theme/theme.conf" | sudo tee -a $BOOT/refind.conf
[[ ! -z $BIG_ICON_SIZE ]] && echo "big_icon_size $BIG_ICON_SIZE" | sudo tee -a $BOOT/refind.conf
[[ ! -z $SMALL_ICON_SIZE ]] && echo "small_icon_size $SMALL_ICON_SIZE" | sudo tee -a $BOOT/refind.conf
[[ -f "$BOOT/icons/bg.png" ]] && echo "banner icons/bg.png" | sudo tee -a $BOOT/refind.conf
