#!/bin/bash

opts=$(cat <<EOF
install=action=store_true=help=Install themes from internet (github)
set=action=store_true=help=Set theme from installed themes
background=type=str=Give a png image to set as background

EOF
)

ESP=$(cat /etc/fstab | sed '/\#/d' | grep "/boot/efi")
[[ -z $ESP ]] && ESP="/efiboot/EFI/refind" || ESP=/boot/efi/EFI/refind

themes="https://raw.githubusercontent.com/FT-Labs/phyOS-refind-themes/master/themes.txt"
themes="EXIT $(curl --silent $themes)"

args=$(printf "$opts" | pygetopts "$@")
eval "$args" &> /dev/null || (echo "$args" | sed 's/pygetopts/refind-theme/g' && exit)

if [[ ! -z $install ]]; then
    install=$(gum choose $themes)
    [[ $install = "EXIT" ]] && exit 0
    sudo mkdir -p /usr/share/refind/themes
    curl -L https://github.com/FT-Labs/phyOS-refind-themes/raw/master/$install.tar.gz | sudo tar xf - -C /usr/share/refind/themes/
elif [[ ! -z $set ]]; then
    theme=$(ls /usr/share/refind/themes)
    chosen=$(gum choose $theme)
    sudo mkdir -p $ESP/theme/
    sudo rm -rf $ESP/theme/*
    sudo cp -rf /usr/share/refind/themes/$chosen/* $ESP
    echo "$chosen theme set succesfully"
fi

if [[ ! -z $background ]]; then
    [[ $(echo "$background" | tr "." " " | awk '{print $NF}') != "png" ]] && echo "Please use a .png image... Aborting" && exit
    sudo cp -f "$background" /icons/bg.png
    sudo refind-mkconfig
fi
